In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from sklearn.pipeline import make_pipeline
from sklearn.model_selection import train_test_split
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn.metrics import accuracy_score
from sklearn.model_selection import GridSearchCV

In [31]:
df = pd.read_csv('train.csv')
test = pd.read_csv('test.csv')

In [29]:
print(df.shape, test.shape)
df.head()

(50000, 112) (10000, 111)

   id           0           1  ...          108        109  label
0   0   -4.187822  -13.978846  ...   158.660385 -83.848561      0
1   1   24.094857  -11.570042  ...    40.601941 -36.462574      5
2   2  129.626766  153.361044  ...  -271.184273  63.889350      4
3   3  209.960232    3.723635  ... -1214.900271 -25.435079      1
4   4 -179.133415         NaN  ...   -80.756317 -51.105732      3

[5 rows x 112 columns]

In [4]:
#Разделение данных
X = df.iloc[:,:-1]
y = df['label']
print(X.shape, y.shape)
X.head()

(50000, 111) (50000,)

   id           0           1  ...        107          108        109
0   0   -4.187822  -13.978846  ...   3.190311   158.660385 -83.848561
1   1   24.094857  -11.570042  ...  -2.787521    40.601941 -36.462574
2   2  129.626766  153.361044  ...  76.767352  -271.184273  63.889350
3   3  209.960232    3.723635  ...  41.329913 -1214.900271 -25.435079
4   4 -179.133415         NaN  ... -16.651422   -80.756317 -51.105732

[5 rows x 111 columns]

In [5]:
#Заполнение пропущенных значений
"""
X.fillna(inplace=True, method='bfill')
X.fillna(inplace=True, method='ffill')
test.fillna(inplace=True, method='bfill')
test.fillna(inplace=True, method='ffill')
X = X.iloc[:30000, :-1]
print(X.shape)
X.head()
"""

"\nX.fillna(inplace=True, method='bfill')\nX.fillna(inplace=True, method='ffill')\ntest.fillna(inplace=True, method='bfill')\ntest.fillna(inplace=True, method='ffill')\nX = X.iloc[:30000, :-1]\nprint(X.shape)\nX.head()\n"

In [6]:
#Посмотрим сколько всего пропущенных значений
print(X.dropna().shape, test.dropna().shape)
#из 50000 строк, только 1765 не имеют пропусков на тренировочных даных
# и 385 из 10000 на тестовых данных
# значит пропуски нужно "хорошо" заполнить

(1765, 111) (385, 111)

In [7]:
#Заполнение пропусков средним значением по столбцу
"""
from sklearn.impute import SimpleImputer
imp = SimpleImputer(missing_values=np.nan, strategy='mean')
X = pd.DataFrame(imp.fit_transform(X))
test = pd.DataFrame(imp.fit_transform(test))
"""

"\nfrom sklearn.impute import SimpleImputer\nimp = SimpleImputer(missing_values=np.nan, strategy='mean')\nX = pd.DataFrame(imp.fit_transform(X))\ntest = pd.DataFrame(imp.fit_transform(test))\n"

In [30]:

from sklearn.impute import KNNImputer
imp = KNNImputer(n_neighbors=3)
X = pd.DataFrame(imp.fit_transform(X), columns=X.columns)

In [9]:
imp = KNNImputer(n_neighbors=4)
test = pd.read_csv('test.csv')
test = pd.DataFrame(imp.fit_transform(test), columns=test.columns)

In [10]:
X.head()

    id           0           1  ...        107          108        109
0  0.0   -4.187822  -13.978846  ...   3.190311   158.660385 -83.848561
1  1.0   24.094857  -11.570042  ...  -2.787521    40.601941 -36.462574
2  2.0  129.626766  153.361044  ...  76.767352  -271.184273  63.889350
3  3.0  209.960232    3.723635  ...  41.329913 -1214.900271 -25.435079
4  4.0 -179.133415   11.689463  ... -16.651422   -80.756317 -51.105732

[5 rows x 111 columns]

In [11]:
test.head()

    id          0           1  ...        107         108         109
0  0.0  70.988329  -53.726764  ...  57.155667  349.346501 -143.966616
1  1.0 -99.136105   47.856013  ...  29.497996 -226.758252  -77.972184
2  2.0 -98.412507   95.380702  ... -59.906696  264.088705  -22.603129
3  3.0  21.493182  170.821211  ... -51.957894  353.973430   36.174981
4  4.0 -14.428943  -88.702214  ...   9.064510  252.167868   96.918271

[5 rows x 111 columns]

In [32]:
#Удалим 10000 первых строк и 15 столбцов т.к. они "плохие"
X = df.iloc[11000:,16:-1]
y = df['label'].iloc[11000:]
test = test.iloc[:,16:]
test.head()

           15         16         17  ...        107         108         109
0  347.949901 -20.659918  50.674314  ...  57.155667  349.346501 -143.966616
1  329.702345 -66.815945  19.848216  ...  29.497996 -226.758252  -77.972184
2  -12.043800  37.210904 -27.640646  ... -59.906696  264.088705  -22.603129
3 -123.628311  -2.093535  37.097581  ... -51.957894  353.973430   36.174981
4 -133.013243  78.306440  17.899180  ...   9.064510  252.167868   96.918271

[5 rows x 95 columns]

In [33]:
from sklearn.impute import KNNImputer
imp = KNNImputer(n_neighbors=3)
imp.fit(X)
X = pd.DataFrame(imp.transform(X), columns=X.columns)
test = pd.DataFrame(imp.transform(test), columns=test.columns)

In [34]:
#Нормализация данных 

scaler = StandardScaler()
X = scaler.fit_transform(X)
scaler1 = StandardScaler()
test = scaler1.fit_transform(test)
X = pd.DataFrame(X)
test = pd.DataFrame(test)

In [35]:
#Разделение данных на tran/test выборки
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

In [ ]:
#KNN (N=5)
knn = KNeighborsClassifier(n_neighbors=5, n_jobs=-1)
knn.fit(X_train, y_train)

In [ ]:
pred = knn.predict(X_test)

In [ ]:
accuracy_score(y_test, pred)

0.8678

In [ ]:
#DecisionTree
from sklearn.tree import DecisionTreeClassifier
dtree = DecisionTreeClassifier(random_state=123)
dtree.fit(X_train, y_train)

In [ ]:
pred = dtree.predict(X_test)

In [ ]:
accuracy_score(y_test, pred)

0.7897

In [ ]:
#LogisticRegression
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(n_jobs=-1)
lr.fit(X_train, y_train)

In [ ]:
lr.score(X_test, y_test)

0.674

In [ ]:
pred = lr.predict(X_test)

In [ ]:
accuracy_score(y_test, pred)

0.674

In [ ]:
#GridSearch fo LogisticRegression
from sklearn.model_selection import GridSearchCV
model = LogisticRegression(n_jobs=-1)
grid = {'penalty': ['l1', 'l2', 'elasticnet'],
        'C': [0.01, 0.1, 1, 10, 100]}
search = GridSearchCV(estimator=model, param_grid=grid, n_jobs=-1, scoring='accuracy', cv=5, refit=True)
search.fit(X_train, y_train)

In [ ]:
search.best_params_

{'C': 10, 'penalty': 'l2'}

In [ ]:
pred = search.predict(X_test)
accuracy_score(y_test, pred)

0.6766

In [ ]:
#GridSearch for KNN
model = KNeighborsClassifier(n_jobs=-1)
grid = {'n_neighbors': [3,5,6,7,9],
        'algorithm': ['kd_tree, ball_tree', 'brute']}
search = GridSearchCV(estimator=model, param_grid=grid, n_jobs=-1, scoring='accuracy', cv=5, refit=True)
search.fit(X_train, y_train)

In [ ]:
search.best_params_

{'algorithm': 'brute', 'n_neighbors': 6}

In [ ]:
pred = search.predict(X_test)
accuracy_score(y_test, pred)

0.7208

In [ ]:
#XGBoostClassifier
from xgboost import XGBClassifier
xgb = XGBClassifier(n_estimator=250, n_jobs=-1, random_state=42)
xgb.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimator=250,
              n_estimators=100, n_jobs=-1, nthread=None,
              objective='multi:softprob', random_state=42, reg_alpha=0,
              reg_lambda=1, scale_pos_weight=1, seed=None, silent=None,
              subsample=1, verbosity=1)

In [ ]:
prediction = xgb.predict(X_test)
accuracy_score(y_test, pred)

0.9218

In [ ]:
xgb = XGBClassifier(n_estimators=450, n_jobs=-1, random_state=42)
xgb.fit(X_train, y_train)

XGBClassifier(base_score=0.5, booster='gbtree', colsample_bylevel=1,
              colsample_bynode=1, colsample_bytree=1, gamma=0,
              learning_rate=0.1, max_delta_step=0, max_depth=3,
              min_child_weight=1, missing=None, n_estimators=450, n_jobs=-1,
              nthread=None, objective='multi:softprob', random_state=42,
              reg_alpha=0, reg_lambda=1, scale_pos_weight=1, seed=None,
              silent=None, subsample=1, verbosity=1)

In [ ]:
pred = xgb.predict(X_test)
accuracy_score(y_test,pred)

0.9001

In [ ]:
#LightGBMClassifier
from lightgbm import LGBMClassifier
lgbm = LGBMClassifier(n_estimators=200, n_jobs=-1)
lgbm.fit(X_train, y_train)

LGBMClassifier(boosting_type='gbdt', class_weight=None, colsample_bytree=1.0,
               importance_type='split', learning_rate=0.1, max_depth=-1,
               min_child_samples=20, min_child_weight=0.001, min_split_gain=0.0,
               n_estimators=200, n_jobs=-1, num_leaves=31, objective=None,
               random_state=None, reg_alpha=0.0, reg_lambda=0.0, silent=True,
               subsample=1.0, subsample_for_bin=200000, subsample_freq=0)

In [ ]:
pred = lgbm.predict(X_test)
accuracy_score(y_test, pred)

0.9378

In [ ]:
#GridSearch fot LightGBMClassifier
from lightgbm import LGBMClassifier
model = LGBMClassifier(n_jobs=-1)
grid = {'n_estimators': [350, 450, 550, 650, 900]}
search = GridSearchCV(estimator=model, param_grid=grid, n_jobs=-1, scoring='accuracy', cv=5, refit=True)
search.fit(X_train, y_train)

GridSearchCV(cv=5, estimator=LGBMClassifier(), n_jobs=-1,
             param_grid={'n_estimators': [350, 450, 550, 650, 900]},
             scoring='accuracy')

In [ ]:
search.best_params_

{'n_estimators': 900}

In [ ]:
pred = search.predict(X_test)
accuracy_score(y_test, pred)

0.9531

In [ ]:
#LightGBM (n_estimators=900)
from lightgbm import LGBMClassifier
lgbm = LGBMClassifier(n_estimators=900, n_jobs=-1)
lgbm.fit(X_train,y_train)

LGBMClassifier(n_estimators=900)

In [ ]:
pred = lgbm.predict(X_test)
accuracy_score(y_test, pred)

0.9574

In [ ]:
#Xgboost (n_estimators=1000)
from xgboost import XGBClassifier
xgb = XGBClassifier(n_estimator=1000, n_jobs=-1, random_state=42)
xgb.fit(X_train, y_train)

XGBClassifier(n_estimator=1000, n_jobs=-1, objective='multi:softprob',
              random_state=42)

In [ ]:
pred = xgb.predict(X_test)
accuracy_score(y_test, pred)

0.8098

In [ ]:
#GridSezrchCV SVM
from sklearn.model_selection import GridSearchCV
from sklearn.svm import SVC
param_grid = {'C': [0.7, 1, 1.3, 1.6],
              'kernel': ['rbf', 'linear', 'poly'],
              'degree': [2,3,4,5],
              'decision_function_shape': ['ovo', 'ovr']}
search = GridSearchCV(SVC(), param_grid=param_grid, scoring='accuracy', cv=5, n_jobs=-1, refit=True)
search.fit(X_train, y_train)
pred = search.predict(X_test)
accuracy_score(y_test, pred)

In [36]:
#SVM 
from sklearn.svm import SVC
model = SVC()
model.fit(X_train, y_train)
pred = model.predict(X_test)
accuracy_score(y_test, pred)

0.9671794871794872

In [37]:
#Make submission
sub = model.predict(test)

In [16]:
print(sub.shape)

(10000,)

In [38]:
submission = pd.DataFrame(sub)
#submission = pd.DataFrame(submission, columns=['label'])
#print(type(submission.iloc[:,:5]))
submission.head()

   0
0  4
1  7
2  3
3  4
4  9

In [39]:
sample_sabmission = pd.read_csv('sample_sabmission.csv')
print(sample_sabmission.shape)
sample_sabmission.head()

(10000, 2)

   id  label
0   0      0
1   1      0
2   2      0
3   3      0
4   4      0

In [40]:
sample_sabmission['label'] = submission
sample_sabmission.head()

   id  label
0   0      4
1   1      7
2   2      3
3   3      4
4   4      9

In [41]:
sample_sabmission.to_csv('svm_preproccesing.csv', index=False)

**Вывод**: наилучший score на Kaggle показала модель SVC "из коробки" с удалением первых 15 столбцов и 10000 строк данных, т.к. в них были выбросы\
**Результат**: public 0.972\
           private 0.9686